namespace ClassicalCryptography.Encoder.Chinese;

public readonly partial record struct ChinesePinyin
{
    private static readonly BidirectionalDictionary<string, string> zhuYins = new()
    {
        { "None", "" },
        { "B", "ㄅ" },
        { "P", "ㄆ" },
        { "M", "ㄇ" },
        { "F", "ㄈ" },
        { "D", "ㄉ" },
        { "T", "ㄊ" },
        { "N", "ㄋ" },
        { "L", "ㄌ" },
        { "G", "ㄍ" },
        { "K", "ㄎ" },
        { "H", "ㄏ" },
        { "J", "ㄐ" },
        { "Q", "ㄑ" },
        { "X", "ㄒ" },
        { "ZH", "ㄓ" },
        { "CH", "ㄔ" },
        { "SH", "ㄕ" },
        { "R", "ㄖ" },
        { "Z", "ㄗ" },
        { "C", "ㄘ" },
        { "S", "ㄙ" },

        { "A", "ㄚ" },
        { "O", "ㄛ" },
        { "E", "ㄜ" },
        { "I", "ㄧ" },
        { "U", "ㄨ" },
        { "V", "ㄩ" },
        { "ER", "ㄦ" },
        { "AI", "ㄞ" },
        { "AO", "ㄠ" },
        { "EI", "ㄟ" },
        { "OU", "ㄡ" },
        { "IA", "ㄧㄚ" },
        { "IAO", "ㄧㄠ" },
        { "IE", "ㄧㄝ" },
        { ChineseRhyme.IOU.ToString(), "ㄧㄡ" },
        { "UA", "ㄨㄚ" },
        { "UAI", "ㄨㄞ" },
        { ChineseRhyme.UEI.ToString(), "ㄨㄟ" },
        { "UO", "ㄨㄛ" },
        { "VE", "ㄩㄝ" },
        { "AN", "ㄢ" },
        { "ANG", "ㄤ" },
        { "EN", "ㄣ" },
        { "ENG", "ㄥ" },
        { "IAN", "ㄧㄢ" },
        { "IANG", "ㄧㄤ" },
        { "IN", "ㄧㄣ" },
        { "ING", "ㄧㄥ" },
        { "UAN", "ㄨㄢ" },
        { "UANG", "ㄨㄤ" },
        { ChineseRhyme.UEN.ToString(), "ㄨㄣ" },
        { ChineseRhyme.ONG.ToString(), "ㄨㄥ" },
        { "VAN", "ㄩㄢ" },
        { "VN", "ㄩㄣ" },
        { "IONG", "ㄩㄥ" },
    };
}
