//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicalCryptography.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassicalCryptography.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ﾟωﾟﾉ= /｀ｍ´）ﾉ ~┻━┻   //*´∇｀*/ [&apos;_&apos;]; o=(ﾟｰﾟ)  =_=3; c=(ﾟΘﾟ) =(ﾟｰﾟ)-(ﾟｰﾟ); (ﾟДﾟ) =(ﾟΘﾟ)= (o^_^o)/ (o^_^o);(ﾟДﾟ)={ﾟΘﾟ: &apos;_&apos; ,ﾟωﾟﾉ : ((ﾟωﾟﾉ==3) +&apos;_&apos;) [ﾟΘﾟ] ,ﾟｰﾟﾉ :(ﾟωﾟﾉ+ &apos;_&apos;)[o^_^o -(ﾟΘﾟ)] ,ﾟДﾟﾉ:((ﾟｰﾟ==3) +&apos;_&apos;)[ﾟｰﾟ] }; (ﾟДﾟ) [ﾟΘﾟ] =((ﾟωﾟﾉ==3) +&apos;_&apos;) [c^_^o];(ﾟДﾟ) [&apos;c&apos;] = ((ﾟДﾟ)+&apos;_&apos;) [ (ﾟｰﾟ)+(ﾟｰﾟ)-(ﾟΘﾟ) ];(ﾟДﾟ) [&apos;o&apos;] = ((ﾟДﾟ)+&apos;_&apos;) [ﾟΘﾟ];(ﾟoﾟ)=(ﾟДﾟ) [&apos;c&apos;]+(ﾟДﾟ) [&apos;o&apos;]+(ﾟωﾟﾉ +&apos;_&apos;)[ﾟΘﾟ]+ ((ﾟωﾟﾉ==3) +&apos;_&apos;) [ﾟｰﾟ] + ((ﾟДﾟ) +&apos;_&apos;) [(ﾟｰﾟ)+(ﾟｰﾟ)]+ ((ﾟｰﾟ==3) +&apos;_&apos;) [ﾟΘﾟ]+((ﾟｰﾟ==3) +&apos;_&apos;) [(ﾟｰﾟ) - (ﾟΘﾟ)]+(ﾟДﾟ) [&apos;c&apos;]+((ﾟДﾟ)+&apos;_&apos;) [ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string AAEncodingString {
            get {
                return ResourceManager.GetString("AAEncodingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 89AZazÆÆÐÐØØÞßææððøøþþĐđĦħııĸĸŁłŊŋŒœŦŧƀƟƢƮƱǃǝǝǤǥǶǷȜȝȠȥȴʯͰͳͶͷͻͽͿͿΑΡΣΩαωϏϏϗϯϳϳϷϸϺϿЂЂЄІЈЋЏИКикяђђєіјћџѵѸҁҊӀӃӏӔӕӘәӠӡӨөӶӷӺԯԱՖաֆאתװײؠءاؿفي٠٩ٮٯٱٴٹڿہہۃےەەۮۼۿۿܐܐܒܯݍޥޱޱ߀ߪࠀࠕࡀࡘࡠࡪࢠࢴࢶࢽऄनपरलळवहऽऽॐॐॠॡ०९ॲঀঅঌএঐওনপরললশহঽঽৎৎৠৡ০ৱ৴৹ৼৼਅਊਏਐਓਨਪਰਲਲਵਵਸਹੜੜ੦੯ੲੴઅઍએઑઓનપરલળવહઽઽૐૐૠૡ૦૯ૹૹଅଌଏଐଓନପରଲଳଵହଽଽୟୡ୦୯ୱ୷ஃஃஅஊஎஐஒஓககஙசஜஜஞடணதநபமஹௐௐ௦௲అఌఎఐఒనపహఽఽౘౚౠౡ౦౯౸౾ಀಀಅಌಎಐಒನಪಳವಹಽಽೞೞೠೡ೦೯ೱೲഅഌഎഐഒഺഽഽൎൎൔൖ൘ൡ൦൸ൺൿඅඖකනඳරලලවෆ෦෯กะาาเๅ๐๙ກຂຄຄງຈຊຊຍຍດທນຟມຣລລວວສຫອະາາຽຽເໄ໐໙ໞໟༀༀ༠༳ཀགངཇཉཌཎདནབམཛཝཨཪཬྈྌကဥဧဪဿ၉ၐၕ 的本地化字符串。
        /// </summary>
        internal static string Base2048PairString {
            get {
                return ResourceManager.GetString("Base2048PairString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ҠҿԀԟڀڿݠޟ߀ߟကဟႠႿᄀᅟᆀᆟᇠሿበቿዠዿጠጿᎠᏟᐠᙟᚠᛟកសᠠᡟᣀᣟᦀᦟ᧠᧿ᨠᨿᯀᯟᰀᰟᴀᴟ⇠⇿⋀⋟⍀⏟␀␟─❟➀➿⠀⥿⦠⦿⨠⩟⪀⪿⫠⭟ⰀⰟⲀⳟⴀⴟⵀⵟ⺠⻟㇀㇟㐀䶟䷀龿ꀀꑿ꒠꒿ꔀꗿꙀꙟꚠꛟ꜀ꝟꞀꞟꡀꡟ 的本地化字符串。
        /// </summary>
        internal static string Base32768PairString {
            get {
                return ResourceManager.GetString("Base32768PairString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Base65536 {
            get {
                object obj = ResourceManager.GetObject("Base65536", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 ⠀⢀⠠⢠⠐⢐⠰⢰⠈⢈⠨⢨⠘⢘⠸⢸⡀⣀⡠⣠⡐⣐⡰⣰⡈⣈⡨⣨⡘⣘⡸⣸⠄⢄⠤⢤⠔⢔⠴⢴⠌⢌⠬⢬⠜⢜⠼⢼⡄⣄⡤⣤⡔⣔⡴⣴⡌⣌⡬⣬⡜⣜⡼⣼⠂⢂⠢⢢⠒⢒⠲⢲⠊⢊⠪⢪⠚⢚⠺⢺⡂⣂⡢⣢⡒⣒⡲⣲⡊⣊⡪⣪⡚⣚⡺⣺⠆⢆⠦⢦⠖⢖⠶⢶⠎⢎⠮⢮⠞⢞⠾⢾⡆⣆⡦⣦⡖⣖⡶⣶⡎⣎⡮⣮⡞⣞⡾⣾⠁⢁⠡⢡⠑⢑⠱⢱⠉⢉⠩⢩⠙⢙⠹⢹⡁⣁⡡⣡⡑⣑⡱⣱⡉⣉⡩⣩⡙⣙⡹⣹⠅⢅⠥⢥⠕⢕⠵⢵⠍⢍⠭⢭⠝⢝⠽⢽⡅⣅⡥⣥⡕⣕⡵⣵⡍⣍⡭⣭⡝⣝⡽⣽⠃⢃⠣⢣⠓⢓⠳⢳⠋⢋⠫⢫⠛⢛⠻⢻⡃⣃⡣⣣⡓⣓⡳⣳⡋⣋⡫⣫⡛⣛⡻⣻⠇⢇⠧⢧⠗⢗⠷⢷⠏⢏⠯⢯⠟⢟⠿⢿⡇⣇⡧⣧⡗⣗⡷⣷⡏⣏⡯⣯⡟⣟⡿⣿ 的本地化字符串。
        /// </summary>
        internal static string BrailleEncodingString {
            get {
                return ResourceManager.GetString("BrailleEncodingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] CommercialCode {
            get {
                object obj = ResourceManager.GetObject("CommercialCode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] FourCorner {
            get {
                object obj = ResourceManager.GetObject("FourCorner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 {0}=~[];{0}={{___:++{0},$$$$:(![]+&quot;&quot;)[{0}],__$:++{0},$_$_:(![]+&quot;&quot;)[{0}],_$_:++{0},$_$$:({{}}+&quot;&quot;)[{0}],$$_$:({0}[{0}]+&quot;&quot;)[{0}],_$$:++{0},$$$_:(!&quot;&quot;+&quot;&quot;)[{0}],$__:++{0},$_$:++{0},$$__:({{}}+&quot;&quot;)[{0}],$$_:++{0},$$$:++{0},$___:++{0},$__$:++{0}}};{0}.$_=({0}.$_={0}+&quot;&quot;)[{0}.$_$]+({0}._$={0}.$_[{0}.__$])+({0}.$$=({0}.$+&quot;&quot;)[{0}.__$])+((!{0})+&quot;&quot;)[{0}._$$]+({0}.__={0}.$_[{0}.$$_])+({0}.$=(!&quot;&quot;+&quot;&quot;)[{0}.__$])+({0}._=(!&quot;&quot;+&quot;&quot;)[{0}._$_])+{0}.$_[{0}.$_$]+{0}.__+{0}._$+{0}.$;{0}.$$={0}.$+(!&quot;&quot;+&quot;&quot;)[{0}._$$]+{0}.__+{0}._+{0}.$+{0} [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string JJEncodngString {
            get {
                return ResourceManager.GetString("JJEncodngString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [][(![]+[])[!![]+!![]+!![]]+({}+[])[+!![]]+(!![]+[])[+!![]]+(!![]+[])[+[]]][({}+[])[!![]+!![]+!![]+!![]+!![]]+({}+[])[+!![]]+({}[[]]+[])[+!![]]+(![]+[])[!![]+!![]+!![]]+(!![]+[])[+[]]+(!![]+[])[+!![]]+({}[[]]+[])[+[]]+({}+[])[!![]+!![]+!![]+!![]+!![]]+(!![]+[])[+[]]+({}+[])[+!![]]+(!![]+[])[+!![]]] 的本地化字符串。
        /// </summary>
        internal static string JotherFunction {
            get {
                return ResourceManager.GetString("JotherFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 []+[][(![]+[])[!![]+!![]+!![]]+({}+[])[+!![]]+(!![]+[])[+!![]]+(!![]+[])[+[]]][({}+[])[!![]+!![]+!![]+!![]+!![]]+({}+[])[+!![]]+({}[[]]+[])[+!![]]+(![]+[])[!![]+!![]+!![]]+(!![]+[])[+[]]+(!![]+[])[+!![]]+({}[[]]+[])[+[]]+({}+[])[!![]+!![]+!![]+!![]+!![]]+(!![]+[])[+[]]+({}+[])[+!![]]+(!![]+[])[+!![]]]((!![]+[])[+!![]]+(!![]+[])[!![]+!![]+!![]]+(!![]+[])[+[]]+({}[[]]+[])[+[]]+(!![]+[])[+!![]]+({}[[]]+[])[+!![]]+({}+[])[!![]+!![]+!![]+!![]+!![]+!![]+!![]]+(![]+[])[!![]+!![]]+({}+[])[+!![]]+({}+[])[!![]+!![]+! [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string JotherLocalString {
            get {
                return ResourceManager.GetString("JotherLocalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字他它新叶在多合或部分用孩客朋友激烈现象只而已化食物事二球睛同勃鸟月允王皇帝没有次每卡路坐比印度尼西章黑向木母上班肉玻璃碎片死千最常福跟再来冰封的错今年流行注捣蛋版手继忘失丹病衣服幼气说小猪亲川火值星文之办元代理背世出可以真时美亮空颓也是灰色光更音小男味道正到急大叔太傻巫婆下安全不本天要易如抱你人民共和追寻打么简单绝湖南定会我张家界的省天了走真明我把泥土脏永玉少回女寸哈义正令台幸青书贵乐儿子言盲口亏甘左布北生白他力老有好呀花月溅守来楼两毒蛋明喜犬马牛羊虫香泉田白心鹿马鱼贝飞士月炎伞门风甜亚龙虎耳立女呆水山万与丑专业丛东丝丢两严丧个丰临为丽举么义乌乐乔习乡书买乱争于云亘亚产亩亲亵亸亿仅从仑仓仪们价众优伙会伛伟传伤伥伦伧伪伫体余佣佥侠侣侥侦侧侨侩侪侬俣俦俨俩俪俭债倾偬偻偾偿傥傧储傩儿兑兖党兰关兴兹养兽冁内冈册写军农冢冯冲决况冻净凄凉凌减凑凛几凤凫凭凯击凼凿刍划刘则刚创删别刬刭刽刿剀剂剐剑剥剧劝办务劢动励劲劳势勋勐勚匀匦匮区医华协卖卢卤卧卫却卺厂厅历厉压厌厍厕厢厣厦厨厩厮县叁参叆叇双发变叙叠叶号叹叽吁后吓吕吗吣吨听启吴呒呓呕呖呗员呙呛呜咔咙咛咝咤咴咸哌响哑哒哓哔哕哗哙哜哝哟唛唝唠唡唢唣唤唿啧啬啭啮啰啴啸喷喾嗫嗬嗳嘘 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MarsLanguagePlain {
            get {
                return ResourceManager.GetString("MarsLanguagePlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 芓彵咜噺旪茬哆匼戓蔀汾鼡駭愙萠伖噭烮哯潒呮洏巳囮喰粅倳②浗聙哃葧茑仴尣迋瑝渧莈洧佽烸鉲蕗唑仳茚喥胒覀嶂嫼姠朩毋仩癍禸箥璃誶爿迉芉朂瑺鍢哏洅唻栤葑啲諎紟姩鋶荇紸搗蜑蝂掱繼莣夨丼疒衤垺呦気詤曉豬儭〣吙徝煋攵のかえ玳悝褙卋絀鈳鉯眞塒媄煷涳穨吔昰咴銫咣哽喑尛侽菋噵㊣箌ゑ夶菽呔儍莁嘙丅咹铨鈈夲兲偠噫洳菢伱囚囻囲囷縋尋咑仫簡單絕鍸喃萣茴莪涨镓堺嘚渻忝叻赱嫃朙峩紦苨汢贓詠玊尐囙囡団囧図囸囹囼圉圊圕圚圞ㄦ孓訁吂ロ虧咁咗咘丠苼苩怹仂咾囿恏吖婲冄濺垨逨嘍両蝳疍奣囍猋骉犇羴蟲馫灥畾皛惢麤驫鱻贔飝壵朤燚傘闁闏憇亜龖虤聑竝奻槑沝屾萬與醜專業叢東絲丟兩嚴喪個豐臨為麗舉麼義烏樂喬習鄉書買亂爭於雲亙亞產畝親褻嚲億僅從侖倉儀們價眾優夥會傴偉傳傷倀倫傖偽佇體餘傭僉俠侶僥偵側僑儈儕儂俁儔儼倆儷儉債傾傯僂僨償儻儐儲儺兒兌兗黨蘭關興茲養獸囅內岡冊寫軍農塚馮沖決況凍淨淒涼淩減湊凜幾鳳鳧憑凱擊氹鑿芻劃劉則剛創刪別剗剄劊劌剴劑剮劍剝劇勸辦務勱動勵勁勞勢勳猛勩勻匭匱區醫華協賣盧鹵臥衛卻巹廠廳曆厲壓厭厙廁廂厴廈廚廄廝縣三參靉靆雙發變敘疊葉號歎嘰籲後嚇呂嗎唚噸聽啟吳嘸囈嘔嚦唄員咼嗆嗚哢嚨嚀噝吒噅鹹呱響啞噠嘵嗶噦嘩噲嚌噥喲嘜嗊嘮啢嗩唕喚呼嘖嗇囀齧囉嘽嘯噴嚳囁呵噯噓 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MarsLanguageText {
            get {
                return ResourceManager.GetString("MarsLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] PGPWordList {
            get {
                object obj = ResourceManager.GetObject("PGPWordList", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
